[[bin]]
name = "graphbit"
path = "src/main.rs"

[dependencies]
anyhow = {workspace = true}
clap = {workspace = true}
graphbit-core = {path = "core"}
# Only use jemalloc on Unix systems (not Windows)
[target.'cfg(unix)'.dependencies]
jemallocator = {workspace = true}
reqwest = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}

[dev-dependencies]
async-trait = {workspace = true}
chrono = {workspace = true}
rand = {workspace = true}
tempfile = {workspace = true}

[package]
authors = ["GraphBit Team"]
description = "Declarative framework for agentic workflow automation"
edition = "2021"
license = "MIT"
name = "graphbit-cli"
repository = "https://github.com/InfinitiBit/graphbit"
version = "0.1.0"

# Benchmark-specific optimizations
[profile.bench]
debug = true
inherits = "release"

# Optimized development profile for faster compile times
[profile.dev]
debug = true
opt-level = 1
overflow-checks = true

# Performance optimizations for release builds
[profile.release]
# Reduce binary size and improve cache efficiency
codegen-units = 1
# Enable link-time optimization for better performance
lto = "fat"
# Enable all optimizations
opt-level = 3
# Use panic=abort to reduce binary size and improve performance
panic = "abort"
# Strip debug symbols to reduce binary size
strip = "symbols"

[workspace]
members = [
  "core",
  "python"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = {version = "0.4", features = ["serde"]}
clap = {version = "4.0", features = ["derive"]}
futures = "0.3"
jemallocator = "0.5"
petgraph = "0.6"
pyo3 = {version = "0.24.1", features = ["extension-module"]}
rand = "0.8"
regex = "1.10"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.8"
thiserror = "1.0"
tokio = {version = "1.0", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = {version = "1.0", features = ["v4", "v5", "serde"]}
